# Generated by Django 3.1.2 on 2020-11-19 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('start_date', models.DateField(default=datetime.date(2020, 11, 19))),
                ('end_date', models.DateField(default='')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
