# Generated by Django 3.1.2 on 2020-11-11 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Quicksite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 11, 11)),
        ),
    ]
