# Generated by Django 3.1.2 on 2020-11-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Quicksite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
